spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - "profile"
              - "https://www.googleapis.com/auth/gmail.readonly"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: "authorization_code"
        provider:
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/auth?access_type=offline&prompt=consent"
            token-uri: "https://oauth2.googleapis.com/token"

jwt:
  secret:
    key: ${JWT_SECRET_KEY}