CREATE TABLE users
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email                    VARCHAR(255)                            NOT NULL,
    name                     VARCHAR(255),
    access_token             VARCHAR(255),
    access_token_issued_at   TIMESTAMP WITHOUT TIME ZONE,
    access_token_expires_at  TIMESTAMP WITHOUT TIME ZONE,
    refresh_token            VARCHAR(255),
    refresh_token_issued_at  TIMESTAMP WITHOUT TIME ZONE,
    refresh_token_expires_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);